%% THIS SCRIPT IS OBSOLETE AND IS NOT BEING UPDATED.
%  THE RECOMMENDED WAY TO BUILD THE MEX FUNCTIONS IS USING CMAKE.
%  If updated, however, this script should still work and is therefore kept
%  as an alternative to CMake.

% Hints:
%  To figure out which C++ compiler is installed on your machine, use:
%    mex -setup c++
%  Also possible:
%    myCompiler = mex.getCompilerConfigurations('C++','Selected')

%% Set up compiler flags, sssuming VTK has been installed using MacPorts

vtkIncPath = '/Volumes/bordeaux/opt/local/include/vtk-8.1';
vtkLibPath = '/Volumes/bordeaux/opt/local/lib/';
vtkVersion = '8.1';

flags = { ...
    ['-I' vtkIncPath], ...
    ['-L' vtkLibPath], ...
    ['-lvtkCommonCore-' vtkVersion], ...
    ['-lvtkCommonDataModel-' vtkVersion], ...
    ['-lvtkCommonExecutionModel-' vtkVersion], ...
    ['-lvtkCommonMath-' vtkVersion], ...
    ['-lvtkCommonMisc-' vtkVersion], ...
    ['-lvtkCommonSystem-' vtkVersion], ...
    ['-lvtkFiltersCore-' vtkVersion], ...
    ['-lvtkFiltersExtraction-' vtkVersion], ...
    ['-lvtkFiltersFlowPaths-' vtkVersion], ...
    ['-lvtkFiltersGeneral-' vtkVersion], ...
    ['-lvtkFiltersGeometry-' vtkVersion], ...
    ['-lvtkFiltersModeling-' vtkVersion], ...
    ['-lvtkIOCore-' vtkVersion], ...
    ['-lvtkIOGeometry-' vtkVersion], ...
    ['-lvtkIOLegacy-' vtkVersion], ...
    ['-lvtkIOPLY-' vtkVersion], ...
    ['-lvtkIOXML-' vtkVersion], ...
    '-I../general' ...
};

%% Set up compiler flags, assuming VTK has been installed from source using CMake

% vtkSrcPath = '/usr/VTK-7.1.1/';
% vtkBinPath = '/usr/VTK-7.1.1/build';
% vtkVersion = '7.1';
% 
% flags = { ...
%     ['-I' vtkSrcPath '/Common/Core'], ...
%     ['-I' vtkBinPath '/Common/Core'], ...
%     ['-I' vtkSrcPath '/Common/DataModel'], ...
%     ['-I' vtkBinPath '/Common/DataModel'], ...
%     ['-I' vtkSrcPath '/Common/ExecutionModel'], ...
%     ['-I' vtkBinPath '/Common/ExecutionModel'], ...
%     ['-I' vtkSrcPath '/Common/Misc'], ...
%     ['-I' vtkBinPath '/Common/Misc'], ...
%     ['-I' vtkSrcPath '/Filters/Core'], ...
%     ['-I' vtkBinPath '/Filters/Core'], ...
%     ['-I' vtkSrcPath '/Filters/General'], ...
%     ['-I' vtkBinPath '/Filters/General'], ...
%     ['-I' vtkSrcPath '/Filters/Geometry'], ...
%     ['-I' vtkBinPath '/Filters/Geometry'], ...
%     ['-I' vtkSrcPath '/IO/Core'], ...
%     ['-I' vtkBinPath '/IO/Core'], ...
%     ['-I' vtkSrcPath '/IO/Geometry'], ...
%     ['-I' vtkBinPath '/IO/Geometry'], ...
%     ['-I' vtkSrcPath '/IO/Legacy'], ...
%     ['-I' vtkBinPath '/IO/Legacy'], ...
%     ['-I' vtkSrcPath '/IO/PLY'], ...
%     ['-I' vtkBinPath '/IO/PLY'], ...
%     ['-I' vtkSrcPath '/IO/XML'], ...
%     ['-I' vtkBinPath '/IO/XML'], ...
%     ['-I' vtkSrcPath '/Utilities/KWIML'], ...
%     ['-I' vtkBinPath '/Utilities/KWIML'], ...
%     ['-L' vtkBinPath '/lib'], ...
%     ['-lvtkCommonCore-' vtkVersion], ...
%     ['-lvtkCommonDataModel-' vtkVersion], ...
%     ['-lvtkCommonExecutionModel-' vtkVersion],
%     ['-lvtkCommonMath-' vtkVersion], ...
%     ['-lvtkCommonMisc-' vtkVersion], ...
%     ['-lvtkCommonSystem-' vtkVersion], ... ...
%     ['-lvtkCommonTransforms-' vtkVersion], ...
%     ['-lvtkFiltersCore-' vtkVersion], ...
%     ['-lvtkFiltersGeneral-' vtkVersion], ...
%     ['-lvtkFiltersGeometry-' vtkVersion], ...
%     ['-lvtkIOCore-' vtkVersion], ...
%     ['-lvtkIOGeometry-' vtkVersion], ...
%     ['-lvtkIOLegacy-' vtkVersion], ...
%     ['-lvtkIOPLY-' vtkVersion], ...
%     ['-lvtkIOXML-' vtkVersion], ...
%     ['-lvtkIOXMLParser-' vtkVersion], ...
%     ['-lvtksys-' vtkVersion], ...
%     ['-lvtkexpat-' vtkVersion], ...
%     ['-lvtkzlib-' vtkVersion], ...
%     '-I../general' ...
% };

%% Build MEX functions

mex('../vtkRead/vtkRead.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:}); % '../vtkRead/additionalReaders/vtkOFFReader.cxx'
mex('../vtkWrite/vtkWrite.cxx', '../vtkWrite/additionalWriters/vtkOBJWriter.cxx', '../vtkWrite/additionalWriters/vtkOFFWriter.cxx', '../general/structToVtk.cxx', '../general/common.cxx', flags{:});
mex('../vtkAlignNodesWithElectrodes/vtkAlignNodesWithElectrodes.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkAppendFilter/vtkAppendFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkAppendPolyData/vtkAppendPolyData.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkArrayMapperNearestNeighbor/vtkArrayMapperNearestNeighbor.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkBooleanOperationPolyDataFilter/vtkBooleanOperationPolyDataFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkCellCentroids/vtkCellCentroids.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkCellDataToPointData/vtkCellDataToPointData.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkCleanPolyData/vtkCleanPolyData.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkCleanUnstructuredGrid/vtkCleanUnstructuredGrid.cxx', '../vtkCleanUnstructuredGrid/vtkCleanUnstructuredGridClass.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkConnectivityFilter/vtkConnectivityFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkContourFilter/vtkContourFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkDataSetSurfaceFilter/vtkDataSetSurfaceFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkExtractEdges/vtkExtractEdges.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkFeatureEdges/vtkFeatureEdges.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkStreamTracer/vtkStreamTracer.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkLinearSubdivisionFilter/vtkLinearSubdivisionFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkPointDataToCellData/vtkPointDataToCellData.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkSmoothPolyDataFilter/vtkSmoothPolyDataFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkThreshold/vtkThreshold.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
mex('../vtkTriangleFilter/vtkTriangleFilter.cxx', '../general/structToVtk.cxx', '../general/vtkToStruct.cxx', '../general/common.cxx', flags{:});
